project_id = "kqlvmmvtskdevdsvzqiw"

[functions.mqtt-bridge]
verify_jwt = true

[functions.process-audio-upload]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.create-transaction]
verify_jwt = true